import Foundation

/// A suggested sight mark generated by interpolating from the archer's
/// existing measured marks. Includes residual standard error so callers can
/// surface a confidence indicator — RSE is 0 with exactly 3 marks (the fit
/// is exactly determined) and grows as input marks deviate from the
/// best-fit curve.
struct SightMarkSuggestion: Equatable {
    var distance: Double
    var distanceUnit: DistanceUnit
    var mark: Double
    var residualStandardError: Double
    var sourceMarkCount: Int
}

/// Quadratic least-squares interpolation of sight marks. The fit is honest
/// for interpolation within the marked range and a small extrapolation
/// buffer; we deliberately refuse to extrapolate further because polynomial
/// fits diverge fast outside their support.
enum SightMarkSuggester {

    // MARK: - Tuning

    /// Industry consensus (Precision Cut Archery, Archer's Advantage,
    /// Royston Heath): minimum 3 marks for any kind of curve fit.
    static let minMarkCount = 3

    /// Minimum max-min distance spread between input marks. Industry
    /// guidance is "20 yards apart" — Precision Cut Archery: "we always
    /// recommend a minimum of 20 yards between sight-in distances to
    /// reduce relative measurement error."
    static let minSpreadMeters: Double = 20.0 * DistanceUnit.yards.metersPerUnit

    /// How far past the marked range we'll still suggest. Polynomial
    /// extrapolation diverges fast, so we cap to a small buffer rather
    /// than pretending the fit is honest at unbounded distances.
    static let extrapolationBufferMeters: Double = 5.0 * DistanceUnit.yards.metersPerUnit

    // MARK: - Outcomes

    enum Outcome: Equatable {
        case suggested(SightMarkSuggestion)
        case notEnoughMarks(have: Int)
        case spreadTooSmall(haveMeters: Double)
        case distanceOutOfRange(haveMinMeters: Double, haveMaxMeters: Double)
    }

    // MARK: - Suggest

    /// Returns a suggestion for `distance` (interpreted in `unit`) given
    /// the archer's measured marks. `marks` should already be scoped to
    /// a single arrow — this function does not filter by arrow id.
    /// Synthesized (`isSuggestion == true`) marks are filtered out before
    /// fitting so we never compound past suggestions.
    static func suggest(
        atDistance distance: Double,
        unit: DistanceUnit,
        from marks: [SightMark]
    ) -> Outcome {
        let measured = marks.filter { !$0.isSuggestion }

        guard measured.count >= minMarkCount else {
            return .notEnoughMarks(have: measured.count)
        }

        let xs = measured.map { $0.distanceInMeters }
        let ys = measured.map { $0.mark }
        let minX = xs.min()!
        let maxX = xs.max()!
        let spread = maxX - minX
        guard spread >= minSpreadMeters else {
            return .spreadTooSmall(haveMeters: spread)
        }

        let targetMeters = distance * unit.metersPerUnit
        let lowerBound = minX - extrapolationBufferMeters
        let upperBound = maxX + extrapolationBufferMeters
        guard targetMeters >= lowerBound && targetMeters <= upperBound else {
            return .distanceOutOfRange(haveMinMeters: minX, haveMaxMeters: maxX)
        }

        guard let coeffs = quadraticLeastSquares(xs: xs, ys: ys) else {
            // Degenerate (e.g. all xs collinear at the same value).
            // Spread check above guarantees real spread, but the solve
            // can still bail if the matrix is numerically singular.
            return .spreadTooSmall(haveMeters: spread)
        }

        let predicted = coeffs.a + coeffs.b * targetMeters + coeffs.c * targetMeters * targetMeters

        // Residual standard error: sqrt(SSR / max(1, n - 3)). The 3 is
        // the number of fitted parameters; with n=3 the fit is exact and
        // we report 0 rather than dividing by zero.
        let residuals = zip(xs, ys).map { (x, y) -> Double in
            let yhat = coeffs.a + coeffs.b * x + coeffs.c * x * x
            return y - yhat
        }
        let ssr = residuals.reduce(0) { $0 + $1 * $1 }
        let dof = max(1, measured.count - 3)
        let rse = measured.count == 3 ? 0.0 : sqrt(ssr / Double(dof))

        return .suggested(SightMarkSuggestion(
            distance: distance,
            distanceUnit: unit,
            mark: predicted,
            residualStandardError: rse,
            sourceMarkCount: measured.count
        ))
    }

    // MARK: - Quadratic least-squares

    /// Solves `y = a + b·x + c·x²` in least-squares sense. Returns
    /// `nil` when the normal-equation matrix is numerically singular.
    static func quadraticLeastSquares(
        xs: [Double],
        ys: [Double]
    ) -> (a: Double, b: Double, c: Double)? {
        precondition(xs.count == ys.count)
        let n = Double(xs.count)
        var sx = 0.0, sx2 = 0.0, sx3 = 0.0, sx4 = 0.0
        var sy = 0.0, sxy = 0.0, sx2y = 0.0
        for i in 0..<xs.count {
            let x = xs[i]
            let y = ys[i]
            let x2 = x * x
            let x3 = x2 * x
            let x4 = x2 * x2
            sx += x
            sx2 += x2
            sx3 += x3
            sx4 += x4
            sy += y
            sxy += x * y
            sx2y += x2 * y
        }
        // Normal equations:
        //   [ n   sx   sx2 ] [a]   [sy   ]
        //   [ sx  sx2  sx3 ] [b] = [sxy  ]
        //   [ sx2 sx3  sx4 ] [c]   [sx2y ]
        var matrix: [[Double]] = [
            [n,   sx,  sx2],
            [sx,  sx2, sx3],
            [sx2, sx3, sx4],
        ]
        var rhs: [Double] = [sy, sxy, sx2y]
        guard solve3x3(&matrix, &rhs) else { return nil }
        return (a: rhs[0], b: rhs[1], c: rhs[2])
    }

    /// Gaussian elimination with partial pivoting on a 3x3 system.
    /// `matrix` and `rhs` are mutated; on success `rhs` holds the
    /// solution. Returns false if the system is numerically singular.
    private static func solve3x3(
        _ matrix: inout [[Double]],
        _ rhs: inout [Double]
    ) -> Bool {
        for i in 0..<3 {
            var pivotRow = i
            var pivotVal = abs(matrix[i][i])
            for k in (i+1)..<3 {
                if abs(matrix[k][i]) > pivotVal {
                    pivotVal = abs(matrix[k][i])
                    pivotRow = k
                }
            }
            if pivotVal < 1e-12 { return false }
            if pivotRow != i {
                matrix.swapAt(i, pivotRow)
                rhs.swapAt(i, pivotRow)
            }
            for k in (i+1)..<3 {
                let factor = matrix[k][i] / matrix[i][i]
                for j in i..<3 { matrix[k][j] -= factor * matrix[i][j] }
                rhs[k] -= factor * rhs[i]
            }
        }
        for i in (0...2).reversed() {
            var s = rhs[i]
            if i < 2 { for j in (i+1)..<3 { s -= matrix[i][j] * rhs[j] } }
            rhs[i] = s / matrix[i][i]
        }
        return true
    }
}
